version: "3.8"
networks:
  'my_notes_network': { }
volumes:
  'my_notes_db_data': { }
services:
  db:
    container_name: 'my_notes_postgres'
    image: 'postgres:12.8'
    ports:
      - '5432:5432'
    networks:
      - 'my_notes_network'
    environment:
      POSTGRES_USER: $ENV_DB_USER
      POSTGRES_PASSWORD: $ENV_DB_PASSWORD
      POSTGRES_DB: $ENV_DB_NAME
    volumes:
      - 'my_notes_db_data:/var/lib/postgresql/data'
  backend:
    container_name: 'my_notes_backend'
    image: "my_notes_app:latest"
    depends_on:
      - 'db'
    ports:
      - "8080:8080"
    networks:
      - 'my_notes_network'
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: 'db'
      DB_USER: $ENV_DB_USER
      DB_PASS: $ENV_DB_PASSWORD
      DB_NAME: $ENV_DB_NAME
      WEB_CLIENT_ID: $ENV_GOOGLE_WEB_CLIENT_ID
